kind: pipeline
type: docker
name: default

steps:
  - name: compile
    image: gcc
    commands:
      - for dir in fib fibio quartic rot13; do cd $dir; make; cd ..; done
  - name: webdav
    image: vividboarder/drone-webdav
    file: fibio/fibio
    destination: https://edenprairie.chandlerswift.com/password/fibio
    username:
      from_secret: username
    password:
      from_secret: password
  - name: release_upload
    image: plugins/gitea-release
    settings:
      api_key:
        from_secret: gitea_token
      base_url: https://edenprairie.chandlerswift.com/git
      files:
        - fib/fib*
        - fibio/fibio
        - quartic/finder
        - rot13/rot13
    when:
      event: tag
