kind: pipeline
type: docker
name: default

steps:
  - name: compile
    image: gcc
    commands:
      - for dir in fib fibio quartic rot13; do cd $dir; make; cd ..; done
      - cp rot13/rot13 ./rot13b
  - name: release_upload
    image: plugins/gitea-release
    settings:
      api_key:
        from_secret: gitea_token
      base_url: https://edenprairie.chandlerswift.com/git
      files: README.md
    when:
      event: tag
